### ISSUE TITLE
Windows version doesn’t work on 64 bit

### ISSUE THREAD

**Issue by dejMatt** [huntercas315/EncodedCPP#16]
Error that software was compiled for 32 bit

**Comment by dejMatt** [comment]
Good idea

**Comment by dejMatt** [comment]
Smart

**Comment by dejMatt** [comment]
Intellectual

**Comment by cassiopeia315** [comment]
> Smart

**no**

**Comment by dejMatt** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
E
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by dejMatt** [comment]
![Uploading 2443D9B4-1268-4922-8F86-0BC71060C307.png…]()

**Comment by cassiopeia315** [comment]
Note to self:
> Just needs to be recompiled as 64 bit I guess?
